"""
Machine Learning Model Training

This module is responsible for training the predictive model used by the ML-based
trading strategy. It loads a pre-labeled dataset, splits it into training and
testing sets, trains a LightGBM classifier, evaluates its performance, and saves
the trained model artifact for later use in signal generation.
"""

import pandas as pd
import joblib
import lightgbm as lgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from typing import Dict, Any

# Define the path for the final model artifact
MODEL_PATH = "ml/model.pkl"
DEFAULT_DATA_PATH = 'ml/labeled_data.csv'

def train_model(data_path: str = DEFAULT_DATA_PATH) -> Dict[str, Any]:
    """
    Trains a LightGBM model on labeled feature data and saves it.

    This function performs the following steps:
    1. Loads a CSV file containing features and a target 'label' column.
    2. Splits the data into training and testing sets.
    3. Initializes and trains a LightGBM multiclass classifier.
    4. Evaluates the model's performance on the test set.
    5. Saves the trained model to a file using joblib.

    Args:
        data_path (str): The path to the labeled CSV data file.

    Returns:
        Dict[str, Any]: A dictionary containing the trained model object
                        and the classification report from the evaluation.
    """
    print(f"Loading data from '{data_path}'...")
    df = pd.read_csv(data_path, index_col='time', parse_dates=True)

    # The 'label' column is our target variable: 1 (buy), -1 (sell), 0 (hold)
    X = df.drop(columns=['label', 'symbol'])
    y = df['label']

    # Stratified split to maintain label distribution in train/test sets
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )
    print(f"Data split into {len(X_train)} training samples and {len(X_test)} testing samples.")

    # Initialize and train the LightGBM model
    print("Training LightGBM model...")
    model = lgb.LGBMClassifier(
        objective='multiclass',
        num_class=3, # Corresponds to buy (1), sell (-1), hold (0)
        random_state=42
    )
    model.fit(X_train, y_train)

    # Evaluate the model's performance
    print("\nEvaluating model performance on the test set...")
    y_pred = model.predict(X_test)
    report = classification_report(y_test, y_pred, target_names=['sell (-1)', 'hold (0)', 'buy (1)'])
    print("Model Evaluation Report:")
    print(report)

    # Save the trained model artifact
    print(f"Saving trained model to '{MODEL_PATH}'...")
    joblib.dump(model, MODEL_PATH)
    print("Model training complete and artifact saved.")

    return {"model": model, "classification_report": report}

if __name__ == '__main__':
    # This block allows the script to be run directly to train the model.
    # It requires a 'labeled_data.csv' file in the 'ml/' directory.
    # This file would typically be generated by a separate data preparation/labeling script.
    try:
        train_model()
    except FileNotFoundError:
        print(f"\nError: Labeled data file not found at '{DEFAULT_DATA_PATH}'.")
        print("Please ensure you have a prepared dataset before running the training script.")
    except Exception as e:
        print(f"\nAn unexpected error occurred during model training: {e}")
