"""A service for active risk management and automated de-risking.

This module provides a standalone microservice that acts as an automated
"circuit breaker" for the trading system. It subscribes to the `risk_reports`
event stream, listening for alerts generated by the `RiskMonitorService`.

If a `breach` status is detected, it initiates a de-risking protocol, which
involves immediately closing all open positions in the affected portfolio to
prevent further losses.
"""

import sys
import os
import json
import time
import redis
from typing import Dict, Any

# Add parent directory to allow imports from sibling modules
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from portfolio.manager import get_portfolio_status, execute_trade

def run_risk_manager_service():
    """The main entry point and infinite loop for the risk manager service.

    This function establishes a connection to Redis, creates a consumer group
    for the `risk_reports` stream, and enters an infinite loop. Inside the
    loop, it blocks and waits for new risk reports. If a report indicates a
    breach, it triggers the `flatten_portfolio` function.
    """
    redis_client = redis.Redis(host=os.getenv("REDIS_HOST", "localhost"), port=int(os.getenv("REDIS_PORT", 6379)), db=0)
    stream_name = 'risk_reports'
    group_name = 'risk_manager_group'
    worker_name = f'risk_manager_worker_{os.getpid()}'

    try:
        redis_client.xgroup_create(stream_name, group_name, id='0', mkstream=True)
    except redis.exceptions.ResponseError as e:
        if "already exists" not in str(e).lower():
            raise

    print("Risk Manager Service started. Listening for risk reports...")

    while True:
        try:
            events = redis_client.xreadgroup(group_name, worker_name, {stream_name: '>'}, count=1, block=0)
            if not events:
                time.sleep(1)
                continue

            for _, messages in events:
                for message_id, message_data in messages:
                    report = {k.decode(): v.decode() for k, v in message_data.items()}

                    if report.get('risk_status') == 'breach':
                        print(f"!!! RISK BREACH DETECTED !!! Portfolio: {report.get('portfolio')}")
                        print(f"Violations: {report.get('violations')}")
                        print("Initiating automated de-risking protocol: FLATTENING PORTFOLIO.")
                        flatten_portfolio(report.get('portfolio', 'default'))

                    redis_client.xack(stream_name, group_name, message_id)

        except Exception as e:
            print(f"An error occurred in the risk manager service loop: {e}")
            time.sleep(10)

def flatten_portfolio(portfolio_name: str):
    """Closes all open positions in a given portfolio.

    This function is the core of the de-risking protocol. It retrieves all
    open positions and executes an opposing trade for each one to neutralize
    the portfolio's exposure.

    Args:
        portfolio_name: The name of the portfolio to flatten.
    """
    print(f"Fetching open positions for portfolio '{portfolio_name}'...")
    try:
        portfolio_status = get_portfolio_status(portfolio_name)
        open_positions = portfolio_status.get('positions', [])

        if not open_positions:
            print("No open positions found to close.")
            return

        for position in open_positions:
            symbol = position['symbol']
            quantity = position['quantity']

            # Determine the side of the closing trade
            # If we have a positive quantity (long), we need to sell.
            # If we have a negative quantity (short), we need to buy to cover.
            side_to_close = 'sell' if quantity > 0 else 'buy'

            print(f"Executing closing trade: {side_to_close.upper()} {abs(quantity)} {symbol}")
            execute_trade(
                portfolio_name=portfolio_name,
                symbol=symbol,
                side=side_to_close,
                quantity=abs(quantity)
                # No signal_id is provided, as this is a risk-driven trade.
            )

        print("Portfolio flattening protocol complete.")

    except Exception as e:
        print(f"An error occurred during portfolio flattening: {e}")

if __name__ == '__main__':
    run_risk_manager_service()
