"""
Signal Generation Engine

This module serves as the core of the signal generation system. It dynamically
loads and executes all available trading strategies (e.g., RSI, MACD, ML-based)
based on the central configuration.

It iterates through the enabled strategies, collects their individual signals,
and returns a consolidated list of raw signals, which are then passed to the
aggregator for weighting and final decision-making.
"""

import json
import os
import sys
from typing import List, Dict, Any

# Add the parent directory to the path to allow imports
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from config.manager import get_config
from signals.strategies import rsi, macd, sentiment, ml_strategy

def generate_signals(symbol: str = 'BTC/USDT') -> List[Dict[str, Any]]:
    """
    Generates a list of raw signals from all enabled trading strategies.

    This function dynamically calls the `generate_signal` function of each
    strategy that is marked as 'enabled' in the system's configuration. It
    filters out any neutral ('hold') signals.

    Args:
        symbol (str): The trading symbol to generate signals for (e.g., 'BTC/USDT').

    Returns:
        List[Dict[str, Any]]: A list of raw signal dictionaries. Each dictionary
                              contains the strategy name, direction, confidence,
                              and the symbol.
    """
    # A registry of all available strategy modules and their signal functions
    strategies = {
        'rsi': rsi.generate_signal,
        'macd': macd.generate_signal,
        'sentiment': sentiment.generate_signal,
        'ml': ml_strategy.generate_signal,
    }

    signals: List[Dict[str, Any]] = []

    # Load the 'strategies' section from the central configuration
    try:
        strategy_config = get_config().get('strategies', {})
    except ValueError:
        print("Warning: Configuration not found. Running with default strategy settings.")
        strategy_config = {'rsi': {'enabled': True}, 'macd': {'enabled': True}}


    for name, generate_func in strategies.items():
        # Execute only the strategies that are enabled in the config
        if strategy_config.get(name, {}).get('enabled', False):
            try:
                direction, confidence = generate_func(symbol)
                # Only include signals that have a clear directional bias
                if direction != 'hold':
                    signals.append({
                        'strategy': name,
                        'direction': direction,
                        'confidence': confidence,
                        'symbol': symbol
                    })
            except Exception as e:
                print(f"Error generating signal from '{name}' strategy: {e}")

    return signals

if __name__ == '__main__':
    # Example Usage:
    # Demonstrates how to generate signals for a specific symbol. The output
    # depends on the current market data and the strategy configuration in the database.

    print("--- Signal Engine Example ---")
    print("Generating signals for BTC/USDT based on current configuration...")

    all_signals = generate_signals('BTC/USDT')

    if all_signals:
        print("\nGenerated Signals:")
        print(json.dumps(all_signals, indent=4))
    else:
        print("\nNo directional signals were generated by the enabled strategies.")
