"""Orchestrates the generation of raw trading signals from various strategies.

This module acts as the central coordinator for the signal generation process.
It dynamically loads and executes all available trading strategies based on the
system's central configuration, which is retrieved from the database.

The main function, `generate_signals`, iterates through the enabled strategies,
invokes their respective signal generation logic, and aggregates the raw signals.
These signals, each tagged with its source strategy and a confidence score, are
then ready to be passed to the signal aggregator for weighting and final
decision-making.
"""

import json
import os
import sys
from typing import List, Dict, Any

# Add the parent directory to the path to allow imports from sibling modules
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from config.manager import get_config
from signals.strategies import rsi, macd, sentiment, ml_strategy

def generate_signals(symbol: str = 'BTC/USDT') -> List[Dict[str, Any]]:
    """Generates a list of raw signals from all enabled trading strategies.

    This function serves as the primary entry point for signal generation. It
    fetches the latest strategy configuration from the database, which specifies
    which strategies are active. It then iterates through a hardcoded registry of
    available strategies, calling the `generate_signal` function for each one
    that is marked as 'enabled'.

    Neutral signals (e.g., 'hold') are filtered out, and the final list contains
    only actionable buy or sell signals.

    Args:
        symbol: The trading symbol for which to generate signals (e.g., 'BTC/USDT').

    Returns:
        A list of raw signal dictionaries. Each dictionary includes the
        source strategy name, the signal direction ('buy' or 'sell'), a
        confidence score (0.0 to 1.0), and the symbol. Returns an empty
        list if no actionable signals are generated.
    """
    # A registry mapping strategy names to their signal generation functions.
    # This allows for dynamic invocation based on the configuration.
    strategies = {
        'rsi': rsi.generate_signal,
        'macd': macd.generate_signal,
        'sentiment': sentiment.generate_signal,
        'ml': ml_strategy.generate_signal,
    }

    signals: List[Dict[str, Any]] = []

    # Load the 'strategies' section from the central configuration
    try:
        strategy_config = get_config().get('strategies', {})
    except ValueError:
        print("Warning: Configuration not found. Running with default strategy settings.")
        strategy_config = {'rsi': {'enabled': True}, 'macd': {'enabled': True}}


    for name, generate_func in strategies.items():
        # Execute only the strategies that are enabled in the config
        if strategy_config.get(name, {}).get('enabled', False):
            try:
                direction, confidence = generate_func(symbol)
                # Only include signals that have a clear directional bias
                if direction != 'hold':
                    signals.append({
                        'strategy': name,
                        'direction': direction,
                        'confidence': confidence,
                        'symbol': symbol
                    })
            except Exception as e:
                print(f"Error generating signal from '{name}' strategy: {e}")

    return signals

if __name__ == '__main__':
    # Example Usage:
    # Demonstrates how to generate signals for a specific symbol. The output
    # depends on the current market data and the strategy configuration in the database.

    print("--- Signal Engine Example ---")
    print("Generating signals for BTC/USDT based on current configuration...")

    all_signals = generate_signals('BTC/USDT')

    if all_signals:
        print("\nGenerated Signals:")
        print(json.dumps(all_signals, indent=4))
    else:
        print("\nNo directional signals were generated by the enabled strategies.")
